languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "文森的科技小站"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  description = "文森的科技小站。"

# 默认站点作者设置
[params.author]
   name = "Vincent Sha"
   email = "vincentshajing@gmail.com"
   image = "img/avatar-sha02.png"
   headline = "文森的科技小站。"
   bio = "文森的科技小站"
   links = [
     { x-twitter = "https://x.com/@vincentshaj" },
     { github = "https:/github.com/vincent-sha" },
     { youtube = "https://www.youtube.com/@vincentsha4819" }
     {facebook = "https://www.facebook.com/vincent.sha.948" }
     {reddit = "https://www.reddit.com/user/vincent-s" }
   ]